name: Enforce PR labels

on: pull_request
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        BANNED_LABELS: "my-banned-label"
